CREATE TABLE IF NOT EXISTS public.portfolio_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  subject TEXT NOT NULL DEFAULT 'Portfolio Contact',
  message TEXT NOT NULL
);

ALTER TABLE public.portfolio_messages
ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS
portfolio_messages_created_at_idx
ON public.portfolio_messages (
  created_at DESC
);
